// Gili Air community group and content
export const giliAirGroup = {
  id: '/gili-air',
  slug: '/gili-air',
  parentId: '/',  
  type: 'group',
  title: 'Gili Air Community',
  content: 'Island life on Gili Air - diving, beaches, and the laid-back lifestyle of Indonesia\'s paradise island',
  view: 'map',
  depiction: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=600&fit=crop',
  tags: ['gili-air', 'indonesia', 'island-life', 'diving', 'beach'],
  latitude: -8.3569,
  longitude: 116.0820,
  radius: 3000, // 3km radius covering the small island
  createdAt: '2024-01-28T08:00:00.000Z',
  updatedAt: '2024-01-28T08:00:00.000Z',
  metadata: {
    memberCount: 287,
    recentPosts: 156,
    isPublic: true
  }
};

// Gili Air posts with specific locations and detailed content
export const giliAirPosts = [
  {
    id: '/gili-air/sunrise-beach-yoga',
    slug: '/gili-air/sunrise-beach-yoga',
    parentId: '/gili-air',
    type: 'post',
    title: 'Sunrise yoga on the east beach',
    content: 'Every morning at 6am, a small group gathers on the east beach for yoga as the sun rises over Lombok. No instructor, no fees - just locals and travelers moving together. Bring your own mat or use the sand. The light at that hour is magical, and you\'ll often see turtles swimming just offshore.',
    depiction: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
    tags: ['yoga', 'sunrise', 'beach', 'community'],
    latitude: -8.3545,
    longitude: 116.0865,
    radius: 100,
    createdAt: '2024-02-01T05:30:00.000Z',
    updatedAt: '2024-02-01T05:30:00.000Z'
  },
  {
    id: '/gili-air/turtle-point-dive',
    slug: '/gili-air/turtle-point-dive',
    parentId: '/gili-air',
    type: 'post',
    title: 'Turtle Point - best dive site for beginners',
    content: 'Turtle Point on the northwest side is perfect for new divers. Shallow reef at 8-12 meters, always calm, and you\'re guaranteed to see green turtles. The coral garden here recovered beautifully after the 2018 earthquake. Go early morning before the day trip boats arrive - you\'ll have the turtles to yourself.',
    depiction: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
    tags: ['diving', 'turtles', 'snorkeling', 'marine-life'],
    latitude: -8.3520,
    longitude: 116.0780,
    radius: 200,
    createdAt: '2024-02-02T08:15:00.000Z',
    updatedAt: '2024-02-02T08:15:00.000Z'
  },
  {
    id: '/gili-air/warung-sunset',
    slug: '/gili-air/warung-sunset',
    parentId: '/gili-air',
    type: 'post',
    title: 'Ibu Made\'s warung - where locals actually eat',
    content: 'Past the main strip, near the mosque, Ibu Made runs a tiny warung from her front porch. No menu - she cooks whatever\'s fresh that day. Her nasi campur is 25k and could feed two people. She remembers everyone\'s name after one visit. The cats are friendly, the portions are huge, and you\'ll be the only tourist there.',
    depiction: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    tags: ['food', 'warung', 'local', 'authentic'],
    latitude: -8.3580,
    longitude: 116.0835,
    radius: 50,
    createdAt: '2024-02-03T12:45:00.000Z',
    updatedAt: '2024-02-03T12:45:00.000Z'
  },
  {
    id: '/gili-air/full-moon-beach',
    slug: '/gili-air/full-moon-beach',
    parentId: '/gili-air',
    type: 'post',
    title: 'Full moon gatherings on the south beach',
    content: 'Every full moon, people gather on the quiet south beach with drums, fire poi, and acoustic guitars. It\'s not organized - it just happens. Bring something to share, respect the vibe, leave no trace. The bioluminescence in the water during full moons is incredible. Wade in and watch the plankton light up around your feet.',
    depiction: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    tags: ['full-moon', 'beach', 'community', 'bioluminescence'],
    latitude: -8.3610,
    longitude: 116.0845,
    radius: 150,
    createdAt: '2024-02-04T19:30:00.000Z',
    updatedAt: '2024-02-04T19:30:00.000Z'
  },
  {
    id: '/gili-air/bike-repair-pak-wayan',
    slug: '/gili-air/bike-repair-pak-wayan',
    parentId: '/gili-air',
    type: 'post',
    title: 'Pak Wayan fixes bikes for whatever you can pay',
    content: 'Blue house near the harbor, look for the pile of bicycle parts. Pak Wayan has been fixing bikes on this island for 30 years. He charges tourists 50k, locals 20k, and if you\'re broke he\'ll do it for free. His grandson is learning the trade. They have every spare part imaginable somehow.',
    depiction: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&h=600&fit=crop',
    tags: ['bicycle', 'repair', 'local-business', 'community'],
    latitude: -8.3565,
    longitude: 116.0810,
    radius: 30,
    createdAt: '2024-02-05T10:20:00.000Z',
    updatedAt: '2024-02-05T10:20:00.000Z'
  },
  {
    id: '/gili-air/secret-snorkel-spot',
    slug: '/gili-air/secret-snorkel-spot',
    parentId: '/gili-air',
    type: 'post',
    title: 'The snorkel spot nobody talks about',
    content: 'Northeast corner, past the last bungalows, there\'s a small rocky outcrop. Swim out about 50 meters and you\'ll find a coral garden that survived the earthquake perfectly. Saw a reef shark there last week. No boats come here because it\'s too shallow. Best at high tide, bring reef-safe sunscreen.',
    depiction: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
    tags: ['snorkeling', 'secret-spot', 'coral', 'marine-life'],
    latitude: -8.3530,
    longitude: 116.0880,
    radius: 100,
    createdAt: '2024-02-06T07:45:00.000Z',
    updatedAt: '2024-02-06T07:45:00.000Z'
  },
  {
    id: '/gili-air/coconut-man',
    slug: '/gili-air/coconut-man',
    parentId: '/gili-air',
    type: 'post',
    title: 'The coconut man who climbs barefoot',
    content: 'Every afternoon around 4pm, Ketut climbs the palms along the west beach to harvest coconuts. He\'s 67 years old and climbs faster than anyone. 15k for a fresh coconut, he\'ll cut it open with his machete right there. Sometimes he brings his grandson who\'s learning. They know which trees have the sweetest water.',
    depiction: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=600&fit=crop',
    tags: ['coconut', 'local-character', 'tradition', 'beach'],
    latitude: -8.3575,
    longitude: 116.0795,
    radius: 200,
    createdAt: '2024-02-07T16:00:00.000Z',
    updatedAt: '2024-02-07T16:00:00.000Z'
  },
  {
    id: '/gili-air/dive-master-training',
    slug: '/gili-air/dive-master-training',
    parentId: '/gili-air',
    type: 'post',
    title: 'Divemaster training - the real story',
    content: 'Did my DM here last year. Three months of early mornings, equipment maintenance, and learning every dive site intimately. The instructors here actually care about creating good divemasters, not just collecting course fees. You\'ll work hard, but you\'ll leave knowing your stuff. The community of DMs and instructors here is tight.',
    depiction: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
    tags: ['diving', 'divemaster', 'training', 'certification'],
    latitude: -8.3560,
    longitude: 116.0825,
    radius: 50,
    createdAt: '2024-02-08T09:30:00.000Z',
    updatedAt: '2024-02-08T09:30:00.000Z'
  },
  {
    id: '/gili-air/night-market-thursday',
    slug: '/gili-air/night-market-thursday',
    parentId: '/gili-air',
    type: 'post',
    title: 'Thursday night market - locals only',
    content: 'Behind the school, Thursday nights after sunset. This is where island families come to eat. Satay, nasi goreng, fresh fish, all cooked over charcoal. Everything is 10-20k. The grandmas selling jajan (snacks) will give you free samples. Bring cash, practice your Indonesian, and don\'t take photos without asking.',
    depiction: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    tags: ['night-market', 'food', 'local', 'thursday'],
    latitude: -8.3590,
    longitude: 116.0830,
    radius: 80,
    createdAt: '2024-02-09T18:45:00.000Z',
    updatedAt: '2024-02-09T18:45:00.000Z'
  },
  {
    id: '/gili-air/trash-hero-cleanup',
    slug: '/gili-air/trash-hero-cleanup',
    parentId: '/gili-air',
    type: 'post',
    title: 'Beach cleanup every Sunday morning',
    content: 'Trash Hero meets at 9am by the main harbor. We walk the beaches with bags and gloves. Usually 20-30 people show up - mix of tourists and locals. After cleanup, there\'s free coffee at one of the cafes. The amount of plastic we collect is heartbreaking but the community effort is beautiful. Kids love helping.',
    depiction: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&h=600&fit=crop',
    tags: ['beach-cleanup', 'environment', 'community', 'trash-hero'],
    latitude: -8.3570,
    longitude: 116.0815,
    radius: 100,
    createdAt: '2024-02-10T08:00:00.000Z',
    updatedAt: '2024-02-10T08:00:00.000Z'
  },
  {
    id: '/gili-air/sunset-swing',
    slug: '/gili-air/sunset-swing',
    parentId: '/gili-air',
    type: 'post',
    title: 'The sunset swing everyone photographs',
    content: 'West beach, you know the one. Yes, there\'s usually a line. Yes, it\'s touristy. But honestly? Swinging out over the water at sunset is pretty magical. Go at low tide for the best photos. The local kids who maintain it ask for 20k donation. They rebuilt it after every storm. Worth it for the memory.',
    depiction: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    tags: ['sunset', 'swing', 'photography', 'instagram'],
    latitude: -8.3575,
    longitude: 116.0790,
    radius: 50,
    createdAt: '2024-02-11T17:30:00.000Z',
    updatedAt: '2024-02-11T17:30:00.000Z'
  },
  {
    id: '/gili-air/freediving-training',
    slug: '/gili-air/freediving-training',
    parentId: '/gili-air',
    type: 'post',
    title: 'Learning to freedive in paradise',
    content: 'The freediving school on the north beach changed my life. Started barely able to hold my breath for 30 seconds, now I can dive to 20 meters. The instructors focus on relaxation and technique, not pushing limits. Training in these clear, calm waters is ideal. The freediving community here is supportive and non-competitive.',
    depiction: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
    tags: ['freediving', 'training', 'ocean', 'meditation'],
    latitude: -8.3540,
    longitude: 116.0840,
    radius: 100,
    createdAt: '2024-02-12T11:15:00.000Z',
    updatedAt: '2024-02-12T11:15:00.000Z'
  },
  {
    id: '/gili-air/cat-sanctuary',
    slug: '/gili-air/cat-sanctuary',
    parentId: '/gili-air',
    type: 'post',
    title: 'The woman who feeds 40 island cats',
    content: 'Nyoman feeds the island\'s stray cats every evening at 6pm behind her guesthouse. She spends her own money on cat food and has gotten many of them spayed/neutered. If you want to help, bring cat food or donate to her fund. The cats are healthy and friendly because of her. She knows each one by name.',
    depiction: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=600&fit=crop',
    tags: ['cats', 'animal-welfare', 'community', 'volunteer'],
    latitude: -8.3585,
    longitude: 116.0820,
    radius: 60,
    createdAt: '2024-02-13T18:00:00.000Z',
    updatedAt: '2024-02-13T18:00:00.000Z'
  },
  {
    id: '/gili-air/mushroom-pizza',
    slug: '/gili-air/mushroom-pizza',
    parentId: '/gili-air',
    type: 'post',
    title: 'The pizza place with the secret menu',
    content: 'Everyone knows about the magic mushroom pizzas, but the real secret is their regular food is incredible. The Italian owner sources buffalo mozzarella from Java. Their margherita is simple perfection. Wood-fired oven, thin crust, fresh basil from their garden. Go for the pizza, stay for the sunset view from their deck.',
    depiction: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=600&fit=crop',
    tags: ['pizza', 'italian', 'food', 'sunset'],
    latitude: -8.3568,
    longitude: 116.0805,
    radius: 40,
    createdAt: '2024-02-14T19:20:00.000Z',
    updatedAt: '2024-02-14T19:20:00.000Z'
  },
  {
    id: '/gili-air/morning-fish-market',
    slug: '/gili-air/morning-fish-market',
    parentId: '/gili-air',
    type: 'post',
    title: 'Fish market at dawn - fresher than fresh',
    content: 'Boats come in around 5:30am with the night\'s catch. By 6am, locals are buying fish for their restaurants and homes. Tuna, mahi mahi, snapper, octopus - all caught within sight of the island. The fishermen will clean and fillet for you. Prices are negotiable but fair. This is how you eat like a local.',
    depiction: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
    tags: ['fish-market', 'seafood', 'local', 'morning'],
    latitude: -8.3572,
    longitude: 116.0812,
    radius: 70,
    createdAt: '2024-02-15T05:45:00.000Z',
    updatedAt: '2024-02-15T05:45:00.000Z'
  },
  {
    id: '/gili-air/massage-ladies',
    slug: '/gili-air/massage-ladies',
    parentId: '/gili-air',
    type: 'post',
    title: 'Beach massage ladies - the real deal',
    content: 'The ladies walking the beach with massage signs aren\'t just tourists traps. Many trained in traditional Balinese massage. Sari, who works the north beach, has hands of steel and will find every knot. 100k for an hour, she brings her mat and oil. Tip well - this is how they support their families.',
    depiction: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
    tags: ['massage', 'beach', 'wellness', 'local-business'],
    latitude: -8.3550,
    longitude: 116.0850,
    radius: 300,
    createdAt: '2024-02-16T14:30:00.000Z',
    updatedAt: '2024-02-16T14:30:00.000Z'
  },
  {
    id: '/gili-air/guitar-circle',
    slug: '/gili-air/guitar-circle',
    parentId: '/gili-air',
    type: 'post',
    title: 'Acoustic jam sessions on the beach',
    content: 'Tuesday and Friday nights, musicians gather at the beach bar on the south side. Bring your instrument or just listen. Mix of travelers and locals, all skill levels welcome. Last week someone had a djembe, someone else a ukulele, and we played until midnight. The bar owner doesn\'t mind as long as you buy a few drinks.',
    depiction: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&h=600&fit=crop',
    tags: ['music', 'jam-session', 'beach', 'community'],
    latitude: -8.3600,
    longitude: 116.0840,
    radius: 80,
    createdAt: '2024-02-17T20:00:00.000Z',
    updatedAt: '2024-02-17T20:00:00.000Z'
  },
  {
    id: '/gili-air/manta-season',
    slug: '/gili-air/manta-season',
    parentId: '/gili-air',
    type: 'post',
    title: 'Manta ray season - when and where',
    content: 'August to October, mantas come to the cleaning stations on the south side. Dive sites: Manta Point and Japanese Wreck. They\'re not guaranteed, but when you see one, it\'s unforgettable. These gentle giants have 4-meter wingspans. Stay calm, don\'t chase, let them come to you. Best visibility early morning.',
    depiction: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
    tags: ['manta-ray', 'diving', 'marine-life', 'season'],
    latitude: -8.3620,
    longitude: 116.0850,
    radius: 500,
    createdAt: '2024-02-18T08:30:00.000Z',
    updatedAt: '2024-02-18T08:30:00.000Z'
  },
  {
    id: '/gili-air/book-exchange',
    slug: '/gili-air/book-exchange',
    parentId: '/gili-air',
    type: 'post',
    title: 'The book exchange shelf that never empties',
    content: 'At the cafe near the harbor, there\'s a shelf with hundreds of books. Take one, leave one. Mostly beach reads and travel guides, but sometimes you find gems. Found a first edition Murakami there once. The cafe owner curates it - removes damaged books, organizes by genre. It\'s become a community library.',
    depiction: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=600&fit=crop',
    tags: ['books', 'exchange', 'reading', 'community'],
    latitude: -8.3565,
    longitude: 116.0818,
    radius: 30,
    createdAt: '2024-02-19T13:15:00.000Z',
    updatedAt: '2024-02-19T13:15:00.000Z'
  },
  {
    id: '/gili-air/storm-protocol',
    slug: '/gili-air/storm-protocol',
    parentId: '/gili-air',
    type: 'post',
    title: 'What to do when storms hit',
    content: 'Rainy season brings serious storms. When the boats stop running, you\'re stuck here - plan accordingly. Stock up on water and snacks. The power often goes out. Locals open their homes if you need shelter. The community pulls together. After the storm, the beach needs cleaning. Everyone helps. This is island life.',
    depiction: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?w=800&h=600&fit=crop',
    tags: ['weather', 'storm', 'safety', 'community'],
    latitude: -8.3575,
    longitude: 116.0825,
    radius: 1000,
    createdAt: '2024-02-20T15:45:00.000Z',
    updatedAt: '2024-02-20T15:45:00.000Z'
  },
  {
    id: '/gili-air/horse-cart-rides',
    slug: '/gili-air/horse-cart-rides',
    parentId: '/gili-air',
    type: 'post',
    title: 'The cidomo drivers and their horses',
    content: 'No cars on this island, just bicycles and horse carts (cidomos). The drivers know every path and shortcut. 50k to go around the island, but negotiate. The horses are well-cared for - the drivers love them. Made, who has the cart with bells, has been driving for 40 years. He\'ll tell you stories about the old days.',
    depiction: 'https://images.unsplash.com/photo-1553696590-4b3f68898333?w=800&h=600&fit=crop',
    tags: ['cidomo', 'horse-cart', 'transport', 'tradition'],
    latitude: -8.3570,
    longitude: 116.0825,
    radius: 200,
    createdAt: '2024-02-21T10:00:00.000Z',
    updatedAt: '2024-02-21T10:00:00.000Z'
  }
];

// Community members on Gili Air
export const giliAirCommunity = [
  {
    id: '/ocean-maya',
    slug: '/ocean-maya',
    title: 'Ocean Maya',
    content: 'Freediving instructor and ocean advocate. Teaching people to explore the underwater world on a single breath.',
    type: 'party',
    tags: ['freediving', 'instructor', 'ocean-conservation'],
    bio: 'AIDA certified freediving instructor. Fell in love with the ocean and never left.',
    occupation: 'Freediving Instructor',
    skills: ['Freediving', 'Breath-hold Training', 'Ocean Safety', 'Marine Biology'],
    depiction: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=400&fit=crop',
    latitude: -8.3540,
    longitude: 116.0840,
    createdAt: '2024-01-28T09:00:00.000Z',
    updatedAt: '2024-01-28T09:00:00.000Z'
  },
  {
    id: '/kai-surya',
    slug: '/kai-surya',
    title: 'Kai Surya',
    content: 'Dive instructor who knows every coral head and fish on this reef. Been diving these waters for 15 years.',
    type: 'party',
    tags: ['diving', 'instructor', 'marine-life'],
    bio: 'PADI Master Instructor. The reef is my office, the ocean is my home.',
    occupation: 'Dive Instructor',
    skills: ['Scuba Diving', 'Underwater Photography', 'Marine Identification', 'Equipment Maintenance'],
    depiction: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=400&fit=crop',
    latitude: -8.3560,
    longitude: 116.0825,
    createdAt: '2024-01-28T09:30:00.000Z',
    updatedAt: '2024-01-28T09:30:00.000Z'
  },
  {
    id: '/luna-bintang',
    slug: '/luna-bintang',
    title: 'Luna Bintang',
    content: 'Yoga teacher and wellness guide. Creating space for healing and transformation on this magical island.',
    type: 'party',
    tags: ['yoga', 'wellness', 'meditation'],
    bio: '500-hour certified yoga teacher. Blending traditional practice with island energy.',
    occupation: 'Yoga Instructor',
    skills: ['Vinyasa Yoga', 'Meditation', 'Breathwork', 'Sound Healing'],
    depiction: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop',
    latitude: -8.3545,
    longitude: 116.0865,
    createdAt: '2024-01-28T10:00:00.000Z',
    updatedAt: '2024-01-28T10:00:00.000Z'
  },
  {
    id: '/marco-rossi',
    slug: '/marco-rossi',
    title: 'Marco Rossi',
    content: 'Italian chef bringing authentic pizza to paradise. Wood-fired perfection with a view of the sunset.',
    type: 'party',
    tags: ['chef', 'pizza', 'italian-food'],
    bio: 'Trained in Naples, cooking in paradise. Life is good.',
    occupation: 'Chef & Restaurant Owner',
    skills: ['Pizza Making', 'Italian Cuisine', 'Wood-fired Cooking', 'Recipe Development'],
    depiction: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=400&fit=crop',
    latitude: -8.3568,
    longitude: 116.0805,
    createdAt: '2024-01-28T10:30:00.000Z',
    updatedAt: '2024-01-28T10:30:00.000Z'
  },
  {
    id: '/nyoman-sari',
    slug: '/nyoman-sari',
    title: 'Nyoman Sari',
    content: 'Born and raised on Gili Air. Runs a family warung and knows everyone on the island. The heart of the community.',
    type: 'party',
    tags: ['local', 'warung-owner', 'community-elder'],
    bio: 'Third generation on this island. Watching it change, keeping traditions alive.',
    occupation: 'Warung Owner',
    skills: ['Indonesian Cooking', 'Community Building', 'Local Knowledge', 'Hospitality'],
    depiction: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=400&fit=crop',
    latitude: -8.3580,
    longitude: 116.0835,
    createdAt: '2024-01-28T11:00:00.000Z',
    updatedAt: '2024-01-28T11:00:00.000Z'
  },
  {
    id: '/reef-guardian',
    slug: '/reef-guardian',
    title: 'Reef Guardian',
    content: 'Marine biologist studying coral recovery after the 2018 earthquake. Documenting the reef\'s resilience.',
    type: 'party',
    tags: ['marine-biology', 'conservation', 'research'],
    bio: 'PhD in Marine Biology. The reef teaches me something new every day.',
    occupation: 'Marine Biologist',
    skills: ['Coral Research', 'Underwater Surveying', 'Data Analysis', 'Conservation'],
    depiction: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=400&fit=crop',
    latitude: -8.3555,
    longitude: 116.0830,
    createdAt: '2024-01-28T11:30:00.000Z',
    updatedAt: '2024-01-28T11:30:00.000Z'
  },
  {
    id: '/sunset-sam',
    slug: '/sunset-sam',
    title: 'Sunset Sam',
    content: 'Photographer capturing the island\'s magic. Every sunset is different, every moment worth preserving.',
    type: 'party',
    tags: ['photographer', 'sunset', 'island-life'],
    bio: 'Came for two weeks, stayed for two years. The light here is addictive.',
    occupation: '  Photographer',
    skills: ['Landscape Photography', 'Underwater Photography', 'Photo Editing', 'Drone Operation'],
    depiction: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop',
    latitude: -8.3575,
    longitude: 116.0790,
    createdAt: '2024-01-28T12:00:00.000Z',
    updatedAt: '2024-01-28T12:00:00.000Z'
  },
  {
    id: '/pak-wayan',
    slug: '/pak-wayan',
    title: 'Pak Wayan',
    content: 'The island\'s bicycle mechanic. Fixing bikes and building community for 30 years.',
    type: 'party',
    tags: ['mechanic', 'bicycles', 'local-legend'],
    bio: 'Every bike has a story. Every repair is a conversation.',
    occupation: 'Bicycle Mechanic',
    skills: ['Bicycle Repair', 'Welding', 'Problem Solving', 'Community Service'],
    depiction: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=400&fit=crop',
    latitude: -8.3565,
    longitude: 116.0810,
    createdAt: '2024-01-28T12:30:00.000Z',
    updatedAt: '2024-01-28T12:30:00.000Z'
  }
];
