// Auto-generated by schema conversion script
// Converted from old flat schema to new component-based schema

export const group = {
  "id": "/berkeley",
  "kind": "group",
  "meta": {
    "slug": "/berkeley",
    "permissions": "public",
    "label": "Berkeley Community",
    "content": "Connect with locals and visitors in Berkeley",
    "view": "map",
    "depiction": "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&h=600&fit=crop",
    "tags": [
      "city",
      "community"
    ],
    "created": "2024-01-25T08:00:00.000Z",
    "updated": "2024-01-25T08:00:00.000Z",
    "props": {
      "memberCount": 1523,
      "recentPosts": 94,
      "isPublic": true
    }
  },
  "location": {
    "lat": 37.8752,
    "lon": -122.2689,
    "rad": 25000,
    "point": {
      "type": "Point",
      "coordinates": [
        -122.2689,
        37.8752
      ]
    }
  },
  "stats": {
    "observers": 1523,
    "children": 94
  }
};

export const test_posts = [
  {
    "id": "/berkeley/post-cheese-board-line",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-cheese-board-line",
      "permissions": "public",
      "label": "The secret to Cheese Board's line",
      "content": "Everyone waits in that massive line, but if you call 15 minutes ahead for pickup, you can walk straight to the register. Also, Tuesday's corn pizza with lime is transcendent. They play live jazz while you wait - last week it was a 70-year-old on accordion who knew every request.",
      "depiction": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop",
      "tags": [
        "pizza",
        "berkeley-institution",
        "north-berkeley"
      ],
      "created": "2024-02-01T10:30:00.000Z",
      "updated": "2024-02-01T10:30:00.000Z",
      "props": {
        "sponsorId": "/maya-chen"
      }
    },
    "location": {
      "lat": 37.8798,
      "lon": -122.2689,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2689,
          37.8798
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-bowl-timing",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-bowl-timing",
      "permissions": "public",
      "label": "Berkeley Bowl at 7:47am on Tuesdays",
      "content": "After years of research: Tuesday 7:47am is peak Berkeley Bowl. Produce just restocked, no crowds, parking everywhere. The mushroom forager delivers at 7:30 - get there before the restaurant buyers. West location has better bulk section, original has better produce. Both have that one checker who knows every PLU code by heart.",
      "depiction": "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop",
      "tags": [
        "grocery",
        "produce",
        "local-knowledge"
      ],
      "created": "2024-02-18T11:15:00.000Z",
      "updated": "2024-02-18T11:15:00.000Z",
      "props": {
        "sponsorId": "/maya-chen"
      }
    },
    "location": {
      "lat": 37.8584,
      "lon": -122.2768,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2768,
          37.8584
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-hidden-creek-swimming",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-hidden-creek-swimming",
      "permissions": "public",
      "label": "The swimming hole locals don't share",
      "content": "Past the Brazil Building in Tilden, take the unmarked trail at the fallen oak. 15 minute hike to a perfect swimming hole. Water's cold even in August. On full moons, people bring guitars and stay past sunset. Leave it cleaner than you found it - we've kept it pristine for decades.",
      "depiction": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&h=400&fit=crop",
      "tags": [
        "swimming",
        "tilden",
        "secret-spot"
      ],
      "created": "2024-02-25T09:45:00.000Z",
      "updated": "2024-02-25T09:45:00.000Z",
      "props": {
        "sponsorId": "/phoenix-lee"
      }
    },
    "location": {
      "lat": 37.9054,
      "lon": -122.2472,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2472,
          37.9054
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-telegraph-vinyl-basement",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-telegraph-vinyl-basement",
      "permissions": "public",
      "label": "The basement collection at Rasputin's",
      "content": "Ask for Marcus at Rasputin Music. He'll take you to the basement where they keep the real collection - first pressings, test prints, the stuff that never makes it upstairs. Cash only, prices aren't marked. He remembers what you like after two visits. Best jazz selection in the Bay.",
      "depiction": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=600&h=400&fit=crop",
      "tags": [
        "vinyl",
        "music",
        "telegraph-ave"
      ],
      "created": "2024-03-03T14:20:00.000Z",
      "updated": "2024-03-03T14:20:00.000Z",
      "props": {
        "sponsorId": "/alex-rivera"
      }
    },
    "location": {
      "lat": 37.8689,
      "lon": -122.2588,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2588,
          37.8689
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-dawn-berkeley-hills",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-dawn-berkeley-hills",
      "permissions": "public",
      "label": "Fire trails at dawn before the dog walkers",
      "content": "Start at the Codornices Park rose garden at 5:30am. Take the fire trail up - you'll have the whole hills to yourself. Watch the fog roll back over the bay as the sun hits. By 7am it's all dogs and runners. There's one spot where you can see from the Golden Gate to San Jose on clear mornings.",
      "depiction": "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
      "tags": [
        "hiking",
        "berkeley-hills",
        "sunrise"
      ],
      "created": "2024-03-10T16:30:00.000Z",
      "updated": "2024-03-10T16:30:00.000Z",
      "props": {
        "sponsorId": "/phoenix-lee"
      }
    },
    "location": {
      "lat": 37.8934,
      "lon": -122.2465,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2465,
          37.8934
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-ashby-flea-market-gems",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-ashby-flea-market-gems",
      "permissions": "public",
      "label": "Ashby Flea Market before the crowds",
      "content": "Get there at 6:30am with a flashlight. The good stuff goes fast. Third row from the back, left side - that's where the estate sale dealers set up. Woman with the blue van has incredible mid-century furniture. Guy in the Raiders cap does cash deals on vintage audio equipment. Bring small bills.",
      "depiction": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop",
      "tags": [
        "flea-market",
        "vintage",
        "ashby"
      ],
      "created": "2024-02-02T14:15:00.000Z",
      "updated": "2024-02-02T14:15:00.000Z",
      "props": {
        "sponsorId": "/jordan-kim"
      }
    },
    "location": {
      "lat": 37.8527,
      "lon": -122.2698,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2698,
          37.8527
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-peoples-park-kitchen",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-peoples-park-kitchen",
      "permissions": "public",
      "label": "The community kitchen that feeds hundreds",
      "content": "Every Sunday at People's Park, 1pm. We cook for anyone who's hungry. No questions, no requirements. Bring vegetables if you can, or just bring yourself. The regular crew has been doing this for 15 years. Sometimes former students come back just to chop onions and catch up.",
      "depiction": "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop",
      "tags": [
        "mutual-aid",
        "community-kitchen",
        "peoples-park"
      ],
      "created": "2024-02-03T09:45:00.000Z",
      "updated": "2024-02-03T09:45:00.000Z",
      "props": {
        "sponsorId": "/casey-wong"
      }
    },
    "location": {
      "lat": 37.8656,
      "lon": -122.2572,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2572,
          37.8656
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-tool-library",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-tool-library",
      "permissions": "public",
      "label": "The tool library that builds community",
      "content": "Berkeley Tool Lending Library - 3 locations, 5000+ tools, completely free with library card. The Saturday repair cafe fixes anything you bring. Old-timers teach you how to use tools you've never seen. They have a seed library too. This place has saved me thousands and taught me everything.",
      "depiction": "https://images.unsplash.com/photo-1530982011887-3cc11cc85693?w=600&h=400&fit=crop",
      "tags": [
        "tools",
        "library",
        "community-resource"
      ],
      "created": "2024-02-04T16:20:00.000Z",
      "updated": "2024-02-04T16:20:00.000Z",
      "props": {
        "sponsorId": "/jordan-kim"
      }
    },
    "location": {
      "lat": 37.8798,
      "lon": -122.2756,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2756,
          37.8798
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-poetry-slam",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-poetry-slam",
      "permissions": "public",
      "label": "Monday night poetry at the Starry Plough",
      "content": "Every Monday, 8pm, Starry Plough pub. Sign up at 7:30 for open mic. The regulars are fierce but welcoming. Bartender gives free drinks to first-timers who get on stage. Some nights Youth Speaks kids show up and blow everyone away. Come for the words, stay for the community.",
      "depiction": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=400&fit=crop",
      "tags": [
        "poetry",
        "open-mic",
        "starry-plough"
      ],
      "created": "2024-02-05T11:10:00.000Z",
      "updated": "2024-02-05T11:10:00.000Z",
      "props": {
        "sponsorId": "/sage-martinez"
      }
    },
    "location": {
      "lat": 37.8553,
      "lon": -122.2903,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2903,
          37.8553
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-cesar-chavez-park-kites",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-cesar-chavez-park-kites",
      "permissions": "public",
      "label": "Where the wind is perfect for kites",
      "content": "Northwest corner of César Chávez Park, 3-6pm when the wind shifts. The kite builders meet here - they'll teach you to make box kites from newspaper and bamboo. One guy flies cameras on his kites and takes aerial photos of the bay. Dogs love chasing the shadows.",
      "depiction": "https://images.unsplash.com/photo-1523895665936-7bfe172b757d?w=600&h=400&fit=crop",
      "tags": [
        "kites",
        "marina",
        "wind-patterns"
      ],
      "created": "2024-02-06T13:25:00.000Z",
      "updated": "2024-02-06T13:25:00.000Z",
      "props": {
        "sponsorId": "/phoenix-lee"
      }
    },
    "location": {
      "lat": 37.8697,
      "lon": -122.3184,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.3184,
          37.8697
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-rose-garden-concerts",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-rose-garden-concerts",
      "permissions": "public",
      "label": "Secret concerts in the Rose Garden amphitheater",
      "content": "First Sunday of each month, 2pm, Berkeley Rose Garden amphitheater. Musicians just show up and play - no permits, no announcements. Last month was a 12-piece brass band. Bring a blanket, maybe some wine in a coffee cup. If parks department shows up, everyone pretends it's a birthday party.",
      "depiction": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop",
      "tags": [
        "music",
        "rose-garden",
        "guerrilla-concerts"
      ],
      "created": "2024-02-07T15:40:00.000Z",
      "updated": "2024-02-07T15:40:00.000Z",
      "props": {
        "sponsorId": "/alex-rivera"
      }
    },
    "location": {
      "lat": 37.8934,
      "lon": -122.2643,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2643,
          37.8934
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-albany-bulb-art",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-albany-bulb-art",
      "permissions": "public",
      "label": "The ever-changing art at Albany Bulb",
      "content": "Albany Bulb changes every time you visit. New sculptures appear overnight - driftwood dragons, rebar phoenixes, painted concrete poems. The castle is still there, built from construction waste. Low tide reveals the old pier pilings you can hop between. Respect the people who live here.",
      "depiction": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop",
      "tags": [
        "art",
        "albany-bulb",
        "found-materials"
      ],
      "created": "2024-02-08T08:55:00.000Z",
      "updated": "2024-02-08T08:55:00.000Z",
      "props": {
        "sponsorId": "/sage-martinez"
      }
    },
    "location": {
      "lat": 37.8894,
      "lon": -122.3256,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.3256,
          37.8894
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-free-clinic",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-free-clinic",
      "permissions": "public",
      "label": "The free clinic that saved my life",
      "content": "Berkeley Free Clinic - no insurance needed, no questions asked. They do everything from checkups to mental health. Volunteer dentists on Thursdays. The peer counselors have been through it all and actually listen. Been running on donations since 1969. This place is sacred.",
      "tags": [
        "healthcare",
        "free-clinic",
        "community-health"
      ],
      "created": "2024-02-09T12:30:00.000Z",
      "updated": "2024-02-09T12:30:00.000Z",
      "props": {
        "sponsorId": "/river-stone"
      }
    },
    "location": {
      "lat": 37.8659,
      "lon": -122.2585,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2585,
          37.8659
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-south-berkeley-gardens",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-south-berkeley-gardens",
      "permissions": "public",
      "label": "The guerrilla gardens of South Berkeley",
      "content": "Every median strip and forgotten corner in South Berkeley has been claimed by gardeners. The woman on Russell grows 20 varieties of tomatoes in the parking strip. Corner of Ashby and MLK has a full herb garden - take what you need. We coordinate on NextDoor to avoid duplicate plantings.",
      "depiction": "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop",
      "tags": [
        "guerrilla-gardening",
        "south-berkeley",
        "community-gardens"
      ],
      "created": "2024-02-10T17:45:00.000Z",
      "updated": "2024-02-10T17:45:00.000Z",
      "props": {
        "sponsorId": "/river-stone"
      }
    },
    "location": {
      "lat": 37.8534,
      "lon": -122.2745,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2745,
          37.8534
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-marina-birds",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-marina-birds",
      "permissions": "public",
      "label": "Dawn bird watching at Berkeley Marina",
      "content": "Berkeley Marina at dawn - over 200 species recorded. The old-timer with the Zeiss binoculars knows them all by call. Pelicans fish off the old pier. In winter, thousands of migrating birds rest here. Bring a thermos of coffee and patience. Magic happens when the fog lifts.",
      "depiction": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop",
      "tags": [
        "birding",
        "marina",
        "wildlife"
      ],
      "created": "2024-02-11T14:20:00.000Z",
      "updated": "2024-02-11T14:20:00.000Z",
      "props": {
        "sponsorId": "/phoenix-lee"
      }
    },
    "location": {
      "lat": 37.8658,
      "lon": -122.3156,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.3156,
          37.8658
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-gilman-diy-shows",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-gilman-diy-shows",
      "permissions": "public",
      "label": "924 Gilman - where punk stays alive",
      "content": "924 Gilman still does all-ages shows, still runs on volunteer power, still charges what you can afford. No racism, no sexism, no homophobia, no major label bands. Help clean up after shows. The bathroom graffiti is a historical document. This place launched Green Day but stayed true.",
      "depiction": "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&h=400&fit=crop",
      "tags": [
        "punk",
        "all-ages",
        "diy-venue"
      ],
      "created": "2024-02-12T10:15:00.000Z",
      "updated": "2024-02-12T10:15:00.000Z",
      "props": {
        "sponsorId": "/alex-rivera"
      }
    },
    "location": {
      "lat": 37.8794,
      "lon": -122.2993,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2993,
          37.8794
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-food-salvage",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-food-salvage",
      "permissions": "public",
      "label": "The food salvage network feeding hundreds",
      "content": "Text 'FOOD' to the number on the Berkeley Bowl dumpster fence. We salvage perfectly good produce they can't sell. Tuesday nights after closing, we sort and distribute. Everything's free. Fed 300 families last week. The amount of waste will radicalize you. Bring boxes and a headlamp.",
      "depiction": "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&h=400&fit=crop",
      "tags": [
        "food-salvage",
        "mutual-aid",
        "zero-waste"
      ],
      "created": "2024-02-13T11:30:00.000Z",
      "updated": "2024-02-13T11:30:00.000Z",
      "props": {
        "sponsorId": "/casey-wong"
      }
    },
    "location": {
      "lat": 37.8576,
      "lon": -122.2668,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2668,
          37.8576
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-tilden-steam-trains",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-tilden-steam-trains",
      "permissions": "public",
      "label": "The real schedule for Tilden's steam trains",
      "content": "Tilden steam trains run weekends, but here's the secret: Tuesday mornings they do test runs. Show up at 10am and they'll often let you ride for free while they check the tracks. The engineer will tell you stories about the 1950s when these trains ran all over the East Bay. Kids lose their minds.",
      "depiction": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
      "tags": [
        "tilden-park",
        "steam-trains",
        "family-fun"
      ],
      "created": "2024-02-14T13:45:00.000Z",
      "updated": "2024-02-14T13:45:00.000Z",
      "props": {
        "sponsorId": "/dakota-blue"
      }
    },
    "location": {
      "lat": 37.9012,
      "lon": -122.2489,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2489,
          37.9012
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-critical-mass",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-critical-mass",
      "permissions": "public",
      "label": "Critical Mass bike rides every last Friday",
      "content": "Last Friday of the month, 6pm, Downtown Berkeley BART. We ride together, take back the streets for an hour. Families, fixies, cargo bikes, everyone. The route's never planned - we decide at each intersection. Drivers honk but most smile. Been going since 1992. Bikes are freedom.",
      "tags": [
        "critical-mass",
        "biking",
        "direct-action"
      ],
      "created": "2024-02-15T16:10:00.000Z",
      "updated": "2024-02-15T16:10:00.000Z",
      "props": {
        "sponsorId": "/ember-garcia"
      }
    },
    "location": {
      "lat": 37.8702,
      "lon": -122.2681,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2681,
          37.8702
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-uc-botanical-garden-nights",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-uc-botanical-garden-nights",
      "permissions": "public",
      "label": "UC Botanical Garden when no one's watching",
      "content": "Security does rounds at 5:15 and 8:30. Between those times, the garden is yours. The redwood grove at sunset is cathedral-quiet. The succulent garden looks alien in moonlight. If you're respectful and quiet, they pretend not to see you. Some of us have been doing this for years.",
      "depiction": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&h=400&fit=crop",
      "tags": [
        "botanical-garden",
        "after-hours",
        "secret-access"
      ],
      "created": "2024-02-16T09:25:00.000Z",
      "updated": "2024-02-16T09:25:00.000Z",
      "props": {
        "sponsorId": "/river-stone"
      }
    },
    "location": {
      "lat": 37.8754,
      "lon": -122.2387,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2387,
          37.8754
        ]
      }
    }
  },
  {
    "id": "/berkeley/post-berkeley-free-box-network",
    "kind": "post",
    "meta": {
      "slug": "/berkeley/post-berkeley-free-box-network",
      "permissions": "public",
      "label": "The free box network of Berkeley",
      "content": "Map of Berkeley's free boxes: Russell & Shattuck (books), Ward & MLK (clothes), Derby & Telegraph (random treasures). The one on Hillegass near Ashby is legendary - found a working espresso machine last week. Take what you need, leave what you don't. It's not trash, it's community redistribution.",
      "tags": [
        "free-boxes",
        "gift-economy",
        "community-sharing"
      ],
      "created": "2024-02-17T12:40:00.000Z",
      "updated": "2024-02-17T12:40:00.000Z",
      "props": {
        "sponsorId": "/casey-wong"
      }
    },
    "location": {
      "lat": 37.8563,
      "lon": -122.2598,
      "point": {
        "type": "Point",
        "coordinates": [
          -122.2598,
          37.8563
        ]
      }
    }
  }
];

export const relations = [
  {
    "id": "/berkeley-parent-/",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley-parent-/",
      "label": "/berkeley is child of /",
      "created": "2024-01-25T08:00:00.000Z",
      "updated": "2024-01-25T08:00:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley",
      "predicate": "childOf",
      "object": "/",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-cheese-board-line-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-cheese-board-line-parent-/berkeley",
      "label": "/berkeley/post-cheese-board-line is child of /berkeley",
      "created": "2024-02-01T10:30:00.000Z",
      "updated": "2024-02-01T10:30:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-cheese-board-line",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-bowl-timing-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-bowl-timing-parent-/berkeley",
      "label": "/berkeley/post-berkeley-bowl-timing is child of /berkeley",
      "created": "2024-02-18T11:15:00.000Z",
      "updated": "2024-02-18T11:15:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-bowl-timing",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-hidden-creek-swimming-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-hidden-creek-swimming-parent-/berkeley",
      "label": "/berkeley/post-hidden-creek-swimming is child of /berkeley",
      "created": "2024-02-25T09:45:00.000Z",
      "updated": "2024-02-25T09:45:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-hidden-creek-swimming",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-telegraph-vinyl-basement-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-telegraph-vinyl-basement-parent-/berkeley",
      "label": "/berkeley/post-telegraph-vinyl-basement is child of /berkeley",
      "created": "2024-03-03T14:20:00.000Z",
      "updated": "2024-03-03T14:20:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-telegraph-vinyl-basement",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-dawn-berkeley-hills-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-dawn-berkeley-hills-parent-/berkeley",
      "label": "/berkeley/post-dawn-berkeley-hills is child of /berkeley",
      "created": "2024-03-10T16:30:00.000Z",
      "updated": "2024-03-10T16:30:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-dawn-berkeley-hills",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-ashby-flea-market-gems-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-ashby-flea-market-gems-parent-/berkeley",
      "label": "/berkeley/post-ashby-flea-market-gems is child of /berkeley",
      "created": "2024-02-02T14:15:00.000Z",
      "updated": "2024-02-02T14:15:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-ashby-flea-market-gems",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-peoples-park-kitchen-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-peoples-park-kitchen-parent-/berkeley",
      "label": "/berkeley/post-peoples-park-kitchen is child of /berkeley",
      "created": "2024-02-03T09:45:00.000Z",
      "updated": "2024-02-03T09:45:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-peoples-park-kitchen",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-tool-library-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-tool-library-parent-/berkeley",
      "label": "/berkeley/post-berkeley-tool-library is child of /berkeley",
      "created": "2024-02-04T16:20:00.000Z",
      "updated": "2024-02-04T16:20:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-tool-library",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-poetry-slam-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-poetry-slam-parent-/berkeley",
      "label": "/berkeley/post-berkeley-poetry-slam is child of /berkeley",
      "created": "2024-02-05T11:10:00.000Z",
      "updated": "2024-02-05T11:10:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-poetry-slam",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-cesar-chavez-park-kites-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-cesar-chavez-park-kites-parent-/berkeley",
      "label": "/berkeley/post-cesar-chavez-park-kites is child of /berkeley",
      "created": "2024-02-06T13:25:00.000Z",
      "updated": "2024-02-06T13:25:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-cesar-chavez-park-kites",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-rose-garden-concerts-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-rose-garden-concerts-parent-/berkeley",
      "label": "/berkeley/post-berkeley-rose-garden-concerts is child of /berkeley",
      "created": "2024-02-07T15:40:00.000Z",
      "updated": "2024-02-07T15:40:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-rose-garden-concerts",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-albany-bulb-art-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-albany-bulb-art-parent-/berkeley",
      "label": "/berkeley/post-albany-bulb-art is child of /berkeley",
      "created": "2024-02-08T08:55:00.000Z",
      "updated": "2024-02-08T08:55:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-albany-bulb-art",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-free-clinic-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-free-clinic-parent-/berkeley",
      "label": "/berkeley/post-berkeley-free-clinic is child of /berkeley",
      "created": "2024-02-09T12:30:00.000Z",
      "updated": "2024-02-09T12:30:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-free-clinic",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-south-berkeley-gardens-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-south-berkeley-gardens-parent-/berkeley",
      "label": "/berkeley/post-south-berkeley-gardens is child of /berkeley",
      "created": "2024-02-10T17:45:00.000Z",
      "updated": "2024-02-10T17:45:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-south-berkeley-gardens",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-marina-birds-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-marina-birds-parent-/berkeley",
      "label": "/berkeley/post-berkeley-marina-birds is child of /berkeley",
      "created": "2024-02-11T14:20:00.000Z",
      "updated": "2024-02-11T14:20:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-marina-birds",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-gilman-diy-shows-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-gilman-diy-shows-parent-/berkeley",
      "label": "/berkeley/post-gilman-diy-shows is child of /berkeley",
      "created": "2024-02-12T10:15:00.000Z",
      "updated": "2024-02-12T10:15:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-gilman-diy-shows",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-food-salvage-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-food-salvage-parent-/berkeley",
      "label": "/berkeley/post-berkeley-food-salvage is child of /berkeley",
      "created": "2024-02-13T11:30:00.000Z",
      "updated": "2024-02-13T11:30:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-food-salvage",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-tilden-steam-trains-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-tilden-steam-trains-parent-/berkeley",
      "label": "/berkeley/post-tilden-steam-trains is child of /berkeley",
      "created": "2024-02-14T13:45:00.000Z",
      "updated": "2024-02-14T13:45:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-tilden-steam-trains",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-critical-mass-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-critical-mass-parent-/berkeley",
      "label": "/berkeley/post-berkeley-critical-mass is child of /berkeley",
      "created": "2024-02-15T16:10:00.000Z",
      "updated": "2024-02-15T16:10:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-critical-mass",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-uc-botanical-garden-nights-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-uc-botanical-garden-nights-parent-/berkeley",
      "label": "/berkeley/post-uc-botanical-garden-nights is child of /berkeley",
      "created": "2024-02-16T09:25:00.000Z",
      "updated": "2024-02-16T09:25:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-uc-botanical-garden-nights",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  },
  {
    "id": "/berkeley/post-berkeley-free-box-network-parent-/berkeley",
    "kind": "edge",
    "meta": {
      "slug": "/berkeley/post-berkeley-free-box-network-parent-/berkeley",
      "label": "/berkeley/post-berkeley-free-box-network is child of /berkeley",
      "created": "2024-02-17T12:40:00.000Z",
      "updated": "2024-02-17T12:40:00.000Z",
      "permissions": "public"
    },
    "relation": {
      "subject": "/berkeley/post-berkeley-free-box-network",
      "predicate": "childOf",
      "object": "/berkeley",
      "rank": 0,
      "weight": 1
    }
  }
];
