
export const pdx_test_users = [
    {
      "id": "/maya-chen",
      "slug": "/maya-chen",
      "title": "Maya Chen",
      "content": "Food enthusiast and chef exploring Portland's culinary landscape. Always hunting for the perfect bowl of ramen.",
      "type": "party",
      "tags": ["chef", "foodie", "ramen-lover"],
      "bio": "Culinary school graduate turned food blogger. I believe every meal tells a story.",
      "occupation": "Chef & Food Blogger",
      "skills": ["Cooking", "Food Photography", "Recipe Development"],
      "depiction": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
      "latitude": 45.5152,
      "longitude": -122.6784,
      "createdAt": "2024-01-15T08:30:00.000Z",
      "updatedAt": "2024-01-15T08:30:00.000Z"
    },
    {
      "id": "/alex-rivera",
      "slug": "/alex-rivera",
      "title": "Alex Rivera",
      "content": "Musician and sound engineer keeping Portland's music scene alive. Catch me at every underground show.",
      "type": "party",
      "tags": ["musician", "sound-engineer", "indie-rock"],
      "bio": "Guitar player by night, sound engineer by day. Music is the universal language.",
      "occupation": "Sound Engineer & Musician",
      "skills": ["Audio Engineering", "Guitar", "Music Production"],
      "depiction": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
      "latitude": 45.5230,
      "longitude": -122.6580,
      "createdAt": "2024-01-16T14:20:00.000Z",
      "updatedAt": "2024-01-16T14:20:00.000Z"
    },
    {
      "id": "/jordan-kim",
      "slug": "/jordan-kim",
      "title": "Jordan Kim",
      "content": "Full-stack developer and maker space enthusiast. Building the future one project at a time.",
      "type": "party",
      "tags": ["developer", "maker", "tech"],
      "bio": "Code by day, build by night. Always looking for the next collaborative project.",
      "occupation": "Full-Stack Developer",
      "skills": ["JavaScript", "Python", "3D Printing", "Electronics"],
      "depiction": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=400&fit=crop",
      "latitude": 45.5051,
      "longitude": -122.6750,
      "createdAt": "2024-01-17T11:45:00.000Z",
      "updatedAt": "2024-01-17T11:45:00.000Z"
    },
    {
      "id": "/sam-taylor",
      "slug": "/sam-taylor",
      "title": "Sam Taylor",
      "content": "Street photographer capturing Portland's authentic moments. Every corner has a story to tell.",
      "type": "party",
      "tags": ["photographer", "street-photography", "visual-storyteller"],
      "bio": "Documenting the soul of Portland through my lens. Available for portraits and events.",
      "occupation": "Photographer",
      "skills": ["Photography", "Photo Editing", "Visual Storytelling"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5200,
      "longitude": -122.6819,
      "createdAt": "2024-01-18T09:15:00.000Z",
      "updatedAt": "2024-01-18T09:15:00.000Z"
    },
    {
      "id": "/casey-wong",
      "slug": "/casey-wong",
      "title": "Casey Wong",
      "content": "Community organizer and mutual aid coordinator. Believe in the power of neighbors helping neighbors.",
      "type": "party",
      "tags": ["community-organizer", "mutual-aid", "activist"],
      "bio": "Building stronger communities through direct action and mutual support.",
      "occupation": "Community Organizer",
      "skills": ["Event Planning", "Volunteer Coordination", "Public Speaking"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5375,
      "longitude": -122.6500,
      "createdAt": "2024-01-19T16:30:00.000Z",
      "updatedAt": "2024-01-19T16:30:00.000Z"
    },
    {
      "id": "/river-stone",
      "slug": "/river-stone",
      "title": "River Stone",
      "content": "Urban gardener and permaculture enthusiast. Growing food and community in the concrete jungle.",
      "type": "party",
      "tags": ["urban-gardener", "permaculture", "sustainability"],
      "bio": "Turning vacant lots into food forests. Teaching others to grow their own medicine and food.",
      "occupation": "Urban Agriculture Specialist",
      "skills": ["Permaculture", "Plant Propagation", "Soil Health", "Composting"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5420,
      "longitude": -122.6630,
      "createdAt": "2024-01-20T13:10:00.000Z",
      "updatedAt": "2024-01-20T13:10:00.000Z"
    },
    {
      "id": "/sage-martinez",
      "slug": "/sage-martinez",
      "title": "Sage Martinez",
      "content": "Poet and spoken word artist weaving stories from the streets of Portland. Words are my paintbrush.",
      "type": "party",
      "tags": ["poet", "spoken-word", "writer"],
      "bio": "Crafting verses that capture the human experience. Host of monthly poetry slams.",
      "occupation": "Poet & Teaching Artist",
      "skills": ["Creative Writing", "Performance", "Workshop Facilitation"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5145,
      "longitude": -122.6710,
      "createdAt": "2024-01-21T10:25:00.000Z",
      "updatedAt": "2024-01-21T10:25:00.000Z"
    },
    {
      "id": "/phoenix-lee",
      "slug": "/phoenix-lee",
      "title": "Phoenix Lee",
      "content": "Fitness trainer and outdoor adventure guide. Pushing limits and exploring Portland's wild side.",
      "type": "party",
      "tags": ["fitness-trainer", "outdoor-guide", "adventure"],
      "bio": "Helping people discover their strength, both physical and mental, through movement and nature.",
      "occupation": "partyl Trainer & Adventure Guide",
      "skills": ["Fitness Training", "Rock Climbing", "Wilderness First Aid", "Nutrition"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5320,
      "longitude": -122.6900,
      "createdAt": "2024-01-22T15:40:00.000Z",
      "updatedAt": "2024-01-22T15:40:00.000Z"
    },
    {
      "id": "/dakota-blue",
      "slug": "/dakota-blue",
      "title": "Dakota Blue",
      "content": "Social worker and community connector. Helping reunite Portland with what it's lost.",
      "type": "party",
      "tags": ["social-worker", "community-helper", "connector"],
      "bio": "Dedicated to helping people find what they're looking for, whether it's a lost pet or a sense of belonging.",
      "occupation": "Social Worker",
      "skills": ["Case Management", "Crisis Intervention", "Community Outreach"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5280,
      "longitude": -122.6590,
      "createdAt": "2024-01-23T12:55:00.000Z",
      "updatedAt": "2024-01-23T12:55:00.000Z"
    },
    {
      "id": "/rowan-clark",
      "slug": "/rowan-clark",
      "title": "Rowan Clark",
      "content": "Game designer and tabletop enthusiast. Creating worlds and bringing people together through play.",
      "type": "party",
      "tags": ["game-designer", "tabletop", "storyteller"],
      "bio": "Designing games that tell stories and build communities. Always up for a good campaign.",
      "occupation": "Game Designer",
      "skills": ["Game Design", "Storytelling", "Illustration", "Playtesting"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5180,
      "longitude": -122.6650,
      "createdAt": "2024-01-24T08:20:00.000Z",
      "updatedAt": "2024-01-24T08:20:00.000Z"
    },
    {
      "id": "/indigo-patel",
      "slug": "/indigo-patel",
      "title": "Indigo Patel",
      "content": "Sustainable architect designing Portland's green future. Every building should give back to the earth.",
      "type": "party",
      "tags": ["architect", "sustainability", "green-design"],
      "bio": "Designing buildings that work with nature, not against it. LEED certified and passionate about regenerative design.",
      "occupation": "Sustainable Architect",
      "skills": ["Sustainable Design", "LEED Certification", "3D Modeling", "Environmental Systems"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5090,
      "longitude": -122.6800,
      "createdAt": "2024-01-25T14:35:00.000Z",
      "updatedAt": "2024-01-25T14:35:00.000Z"
    },
    {
      "id": "/ember-garcia",
      "slug": "/ember-garcia",
      "title": "Ember Garcia",
      "content": "Urban planner and placemaking advocate. Transforming neighborhoods through community-driven design.",
      "type": "party",
      "tags": ["urban-planner", "placemaking", "community-design"],
      "bio": "Believing that the best spaces are created by the people who use them. Let's design our city together.",
      "occupation": "Urban Planner",
      "skills": ["Urban Planning", "Community Engagement", "GIS", "Public Policy"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5350,
      "longitude": -122.6720,
      "createdAt": "2024-01-26T11:50:00.000Z",
      "updatedAt": "2024-01-26T11:50:00.000Z"
    },
    {
      "id": "/storm-johnson",
      "slug": "/storm-johnson",
      "title": "Storm Johnson",
      "content": "Sound artist and location-based music creator. Mapping Portland's sonic landscape one recording at a time.",
      "type": "party",
      "tags": ["sound-artist", "field-recording", "experimental-music"],
      "bio": "Creating musical experiences tied to specific places. The city is my instrument.",
      "occupation": "Sound Artist",
      "skills": ["Field Recording", "Sound Design", "Interactive Media", "Spatial Audio"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5250,
      "longitude": -122.6880,
      "createdAt": "2024-01-27T09:05:00.000Z",
      "updatedAt": "2024-01-27T09:05:00.000Z"
    },
    {
      "id": "/luna-davis",
      "slug": "/luna-davis",
      "title": "Luna Davis",
      "content": "Recipe developer and food preservation expert. Keeping culinary traditions alive while creating new ones.",
      "type": "party",
      "tags": ["recipe-developer", "food-preservation", "culinary-historian"],
      "bio": "Collecting family recipes and creating new ones. Teaching the lost arts of canning, fermenting, and preserving.",
      "occupation": "Culinary Historian & Recipe Developer",
      "skills": ["Recipe Development", "Food Preservation", "Fermentation", "Culinary History"],
      "depiction": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
      "latitude": 45.5120,
      "longitude": -122.6760,
      "createdAt": "2024-01-28T16:15:00.000Z",
      "updatedAt": "2024-01-28T16:15:00.000Z"
    }
]




